### ISSUE TITLE
Can sinric support 800 devices?

### ISSUE THREAD

**Issue by GiampaMan** [kakopappa/sinric#108]
Hi Kakopappa! 
You are doing a great work with Sinric! Is an incredible option to use Alexa in your Esp IoT projects!

I have some questions for you.
Can I put 800 devices on Sinric? Will Alexa and Google Home recognize each device? 
I hope you can answer my question. Have a nice day!

**Comment by kakopappa** [comment]
Thanks

Well, server will be fine, not my back account though. 

Let me elaborate

When you ask Alexa to do something, it sends a request to your Amazon Lambda function. This must be hosted in Amazon NOT any where else. Amazon has a free tier so, if you stay with in your free tier limits you are not being billed, when you exceed the limit you have to pay. So I have done a lot to keep the load to mininum at Amazon eg: Android app for Sinric.

However, Google is fine. They send the action directly to my server.

If you want to connect 800 devices I assume you are selling some kind of a IOT solution and not a small dev. I recommend you to build your skill and host your own server. I can help you if you need.

**Comment by GiampaMan** [comment]
Hi! I am really happy you answered me really fast! 

Sorry for my English. It's not my native language.

Ok it's interesting the points you shared with me. 
I told you to use 800 devices because I was trying to make an air conditioning IoT system. But I don't know If I can use your thermostat to graduate the temperature, so I decided to put one button (switch in your page) separately to controll all temperatures of each air conditioner. Can you explain me If I can use a thermostat for that? 

And other thing. I am interested to make my own server and I want to connect it to Google Home devices and Alexa devices. I need help to do that and I appreciate your help.

**Comment by kakopappa** [comment]
I have implemented thermostatcontroller for thermostat type of devices.
https://github.com/kakopappa/sinric/wiki/Supported-devices-and-their-capabilities.
https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html

So i you create a sinric device with thermostat device type, you should be able to tell Alexa/ Google Home to set the tempreature on a device.  

eg:
User: Alexa, set <device name> to 20

will forward to request to your ESP device and you have to handle it from there

**Comment by GiampaMan** [comment]
Hi! Excellent! I am going to read the information you send me to use the thermostat.

I also want to make a server like Sinric to controll only my own projects, can you help me with detailed information to create it? I am not really advanced In web pages and servers.
I hope you can help me.

**Comment by kakopappa** [comment]
@AshokBaijal I think you can use something like ngrok to host the skill on on Pi. 

If I am not mistaken, problem with ngrok is that it resets the name every 24 hours if you on free version.

**Comment by kakopappa** [comment]
Closing this due to not really an issue. If you have any issues please create another one.
