### ISSUE TITLE
Cannot discover devices

### ISSUE THREAD

**Issue by TetsudouSenpai** [kakopappa/sinric#11]
Alexa does not discover anything. The ESP does receive test signals from sinric.com, but device discovery by Alexa doesn't work.

I have installed the beta version of the skill.

What would you suggest?

**Comment by kakopappa** [comment]
1. Make sure you don't have any devices by the same name already

2. Sometimes Alexa does not send the discovery request to the sinric
server. I have already raised a support ticket for this. Their response
times to support tickets are terrible.

**Comment by TetsudouSenpai** [comment]
Okay, the issue is resolved, all the devices have been discovered! Thank you very much, it worked beautifully!
