### ISSUE TITLE
you got it, setting the reception to 26.4 degree

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#113]
@kakopappa 
Hi
on my Living Room GH mini  if I say
1-command  ------>       Set reception to 26.4 degree.
[WSc] get text: 
 {"deviceId":"xxxx","action":"action.devices.commands.SetTemperature","value":{"temperature":26.5}}

2-command  ------>        Set thermostat to 26.4 degree  (name of thermostat is reception)
 [WSc] get text: 
{"deviceId":"xxxx","action":"action.devices.commands.ThermostatTemperatureSetpoint","value":{"thermostatTemperatureSetpoint":26.39999961853027}}

for both commands GH answer  "**You got it, setting the Reception to 26.4 degrees**"
is that correct ?

**Comment by pico563** [comment]
![screenshot_20180905-230005](https://user-images.githubusercontent.com/24532917/45120846-a4d17500-b15f-11e8-9cfe-ca83eae1042b.png)

**Comment by pico563** [comment]
![screenshot_20180905-230916](https://user-images.githubusercontent.com/24532917/45121255-db5bbf80-b160-11e8-8ea3-a878e7b07cdf.png)

**Comment by kakopappa** [comment]
Yes that’s seems correct. What’s the problem?

**Comment by pico563** [comment]
The first command is for light bulb color temperature in degree Kelvin .( Reception lights)
{"deviceId":"xxxx","action":"action.devices.commands.SetTemperature","value":{"temperature":26.5}}

The minimum color temperature I know is 1000 K so **what is 26.5 ?**


![black_body_visible_spectrum](https://user-images.githubusercontent.com/24532917/45139815-5220a900-b1b1-11e8-99c5-d91ba2f47ac4.gif)

at Device STATES: if I ask **" What is my current light color temperature?"** ---> no answer
https://developers.google.com/actions/smarthome/traits/colortemperature


-----------------------------------------------------------------------------------------------------
The second command is for thermostat temperature in degree  Celsius . ( Reception thermostat){"deviceId":"xxxx","action":"action.devices.commands.ThermostatTemperatureSetpoint","value":{"thermostatTemperatureSetpoint":26.39999961853027}}

google is not differentiating  between the two commands.
at the beginning I thought that both are for thermostat degree .

--------------------------------------------------------------------------------------------------------
please add fan speed control to Sinric so I can use it in my A/C project

https://developers.google.com/actions/smarthome/traits/fanspeed

Thanks

**Comment by Deimos1994** [comment]
@pico563 Hi, this is what you should get for the color temperature (if you use lights): `'{"deviceId":"5b7ad84eeXXXXXXXX4b8d2","action":"action.devices.commands.ColorAbsolute","value":{"color":{"name":"white","temperature":5000}}}'`
For the thermostat I always get this:
`'{"deviceId":"5b2e6d6bXXXXXXX42a8f9","action":"action.devices.commands.ThermostatTemperatureSetpoint","value":{"thermostatTemperatureSetpoint":26.39999961853027}}'
`

But you've said that you getting this: `{"deviceId":"xxxx","action":"action.devices.commands.SetTemperature","value":{"temperature":26.5}}` I've never received this payload, I've tried setting temperature with name, or just saying thermostat, but nothing. Are you sure that you getting this payload? bacause it is strange...

**Comment by pico563** [comment]
@Deimos1994 
yes, you are correct. for me also color temperature  is OK
```
{"deviceId":"xxxx","action":"action.devices.commands.ColorAbsolute","value":{"color":{"name":"cool white","temperature":4000}}}
 {"deviceId":"xxxx","action":"action.devices.commands.BrightnessAbsolute","value":{"brightness":8}}

```
I just tried it again for 26.6 degrees
here is the result.

```
[WSc] get text: {"deviceId":"5b8xxxxf946","action":"action.devices.commands.ThermostatTemperatureSetpoint","value":{"thermostatTemperatureSetpoint":26.60000038146973}}
Sensor OK. NO Warnings
26.12       26.60       °C
26.20       57.50       DHT
[WSc] get text: {"deviceId":"5b8xxxxf946","action":"action.devices.commands.SetTemperature","value":{"temperature":26.5}}


```

**Comment by pico563** [comment]
I really don't know .
now sure, it is not color temperature so what it is ?

**Comment by pico563** [comment]
I will add both on my sketch 

```
         if (action == "action.devices.commands.ThermostatTemperatureSetpoint"  || "action.devices.commands.SetTemperature" ) {
            deg =( json["value"]["thermostatTemperatureSetpoint"] ||  json["value"]["temperature"] );

```
I hope it will work .
thanks

**Comment by pico563** [comment]
@Deimos1994 
`If I understood correctly action.devices.commands.SetTemperature is a trait for devices other than thermostats... you should not receive that.
`

that is correct.  I don't know how it passes through Sinric.

`I think you can try delete the device and then creating it again.`

I will.

**Comment by Deimos1994** [comment]
@pico563 Every device has its traits. Thermostat usually has `action.devices.traits.TemperatureSetting` but in theory it also can have `action.devices.traits.TemperatureControl` and if so then you will probably start to receive `action.devices.commands.SetTemperature` but I don't know how and why it happens.
