### ISSUE TITLE
Not available on Amazon UK

### ISSUE THREAD

**Issue by tofuman0** [kakopappa/sinric#12]
Hi. I can't seem to download the skill from Amazon it isn't showing is the skill list and when I use the link on the sinric site it redirects me to amazon uk.

Thanks.

**Comment by kakopappa** [comment]
It will be ready for UK soon. I will update this when it's ready

**Comment by kakopappa** [comment]
can you check now? It should be available in UK now

**Comment by tofuman0** [comment]
Thanks. It's available now. I'll start testing.
