### ISSUE TITLE
Sinric is down !

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#123]

**Comment by aososam** [comment]
Sinric is down!OMG! my house will burn

**Comment by kcmon** [comment]
Just found Sinric today to incorporate Alexa control over my new Hot Tub Controller that I've been working on.  Uploaded my code and found that it wasn't connecting.  Hopefully it will work when Sinric comes back online.

**Comment by kakopappa** [comment]
sorry guys. I am taking a look what happend

**Comment by kakopappa** [comment]
mongodb being a bitch. fixed now
