### ISSUE TITLE
Webservice disconnected from sinric.com!

### ISSUE THREAD

**Issue by aososam** [kakopappa/sinric#126]
My devices were working perfectly last night, today I cannot connect them to sinric.com, is it just me?

**Comment by kakopappa** [comment]
Hi, today morning I moved the server inside cloudflair due to people sending large payloads and trying to hack the server.

**Comment by aososam** [comment]
Hi! yes I can visit sinric.com and hit the test buttons of all my devices.
but all of them are now showing ¨Webservice disconnected from sinric.com!¨ I am using one NodeMCU and two ESP8266 Generic modules, I also updated the libraries and Boards but the problem persists

**Comment by kakopappa** [comment]
can you try to connect using ip address?

**Comment by noobipaul** [comment]
Hi, I am also seeing the same issue this morning. I am using wemos D1 mini esp8266 modules. Have tried re-flashing 2 modules a few times but still the same issue. Webservice disconnected from sinric.com

**Comment by kakopappa** [comment]
looks like a DNS issue. It may take few mins to reflect. Can you try connecting using IP address please

**Comment by aososam** [comment]
yes I will try that as soon as I can the IP is 104.24.111.26 right?

**Comment by noobipaul** [comment]
I have just tried IP, is this correct --> webSocket.begin("104.24.111.26", 80, "/");
If so the problem gives me the same message Webservice disconnected from sinric.com

**Comment by noobipaul** [comment]
Now I am connecting.
