### ISSUE TITLE
Feature request: Rename device via websockets

### ISSUE THREAD

**Issue by tofuman0** [kakopappa/sinric#13]
Would it be possible to add the functionality to rename the the device from the ESP using websockets and the device ID?

Thanks.

**Comment by kakopappa** [comment]
@tofuman0 

The device id is a GUID that is generated automatically and it cannot be modified. However, device name renaming will be available in the future using the API / Website soon.

**Comment by gizmocuz** [comment]
@kakopappa , thanks for your great skill !, It would be great if we could rename devices via the website

**Comment by kakopappa** [comment]
Renaming devices support has been added.
