### ISSUE TITLE
Skill of Sinric for Spanish market?

### ISSUE THREAD

**Issue by jdecmac** [kakopappa/sinric#140]
Hello,
I really like your Sinric project and in the coming days, Amazon will launch the Amazon echo with Alexa in Spain.

Are you planning to launch the Sinric Skill for Alexa in the Spanish market?

I am doing some projects with ESP8266 and I would love to be able to control them with Alexa through Sinric.

Thank you very much for your work

regards

**Comment by kakopappa** [comment]
Thanks. 

Already. waiting for approval from Amazon.

**Comment by cronos123** [comment]
No news?

**Comment by kakopappa** [comment]
good question. I will take a look what happend.

**Comment by kakopappa** [comment]
Close to two months now.. So I sent them a message. let's see their response.

**Comment by jesusado** [comment]
Hello
I am also interested in your project Sinric Skill for Alexa for the Spanish market.
Still not available in Spanish?

Thank you very much for your work

regards

**Comment by kakopappa** [comment]
Thanks, it’s in the review process. Should complete in few days

**Comment by kakopappa** [comment]
Skill is available now.
https://www.amazon.es/dp/B078RGYWQQ
