### ISSUE TITLE
ColorSpectrum and ColorTemperature trait's on google has been deprecated

### ISSUE THREAD

**Issue by mrmojtabaa** [kakopappa/sinric#143]
hi @kakopappa 
please check this links 

[https://developers.google.com/actions/smarthome/traits/colortemperature](url) ,
[https://developers.google.com/actions/smarthome/traits/colorspectrum](url)

You can see this note . 
> This trait has been deprecated. Use ColorSetting instead.

Please add `ColorSetting` trait for `"action.devices.types.LIGHT"` type.
[https://developers.google.com/actions/smarthome/traits/colorsetting](url)

**Comment by kakopappa** [comment]
Thanks. I will make some time to update this in the next release.

**Comment by kakopappa** [comment]
added to 1.4 release
