### ISSUE TITLE
Thermostat and Google Home cannot report temperature below 0 degree Celsius. 

### ISSUE THREAD

**Issue by Deimos1994** [kakopappa/sinric#148]
Hi, 
I ask GH: **what temperature outside**
GH responds: **Cooling is set to 23, with a current temperature of 25.**
In Amazon Alexa app I see correct temperature (-2), but in GH app it is incorrect.
When temperature higher than 0 degree Celsius then it works fine.
Is it google's bug?
![screenshot_gh_al](https://user-images.githubusercontent.com/31592485/48363173-fc371880-e6ad-11e8-9107-4ef808380bb7.jpg)

**Comment by kakopappa** [comment]
could be a bug in the code. like if temp > 0 send it to GH.. it's never temp > 0 where i live. so i never thought about it 💯

**Comment by Deimos1994** [comment]
@kakopappa, Wow, it works now, did you fix it? GH says: **It's currently -0.5 degrees.**

**Comment by kakopappa** [comment]
Hello. Yes I believe I saw the issue and fixed it in the last update. Sorry
I forgot to update the issue

**Comment by kakopappa** [comment]
I had a temperature > 0 then send the temperature to google condition.

It didn’t occur to me it can be less than 0 because it has never been less
than 15 where I live

**Comment by Deimos1994** [comment]
@kakopappa, Thank you very much, I am closing the issue now.
