### ISSUE TITLE
MULTIPLE_relay_with D1 mini 

### ISSUE THREAD

**Issue by sbe1985** [kakopappa/sinric#159]
HI KAKOPAPPA,

I would like to control multiple relay with one esp8266 connected to sinric, I'm new with this kind of stuff I've try to add some code to your example but doesn't work .... 
Can you add some multiple deviceId example ??

**Comment by kakopappa** [comment]
here is an example for two relays.

change the connected PINs accordinly. 
https://gist.github.com/kakopappa/657fa9d622592cedb54e784152fa31b4

**Comment by sbe1985** [comment]
Thanks so much I've add some more relay on the mini and it works great !
I'll buy you a beer ! cheers :)
