### ISSUE TITLE
Rename devices via website

### ISSUE THREAD

**Issue by gizmocuz** [kakopappa/sinric#160]
It would be great if there was an 'edit' button, where we could edit the device Name/Description in the web interface.
It's a feature that could help with issue https://github.com/kakopappa/sinric/issues/13

**Comment by kakopappa** [comment]
Thanks. Started working on this already.

**Comment by gizmocuz** [comment]
Great !! May i also suggest a small additional 'edit' option, 'alias'. Maybe it would be great if you could add 1 alias for the device name.

For example, i like to say "Set thermostat temperature to 20.5 degrees", someone else in my house likes to say "Set heating temperature to 20.5 degrees".
Currently i have to add two devices

"Turn on Living room" vs "Turn on Lights" is another example

**Comment by kakopappa** [comment]
I have added editing device names support in release 1.4. Adding an "alias" will be supported in a later version. I will create a new issue for this.
