### ISSUE TITLE
Amazon Alexa app is not reporting thermostat temp

### ISSUE THREAD

**Issue by emnik** [kakopappa/sinric#179]
Hi kakopappa!
The Amazon Alexa app is showing the thermostat sinric device which is working as expected regarding voice commands and responses, it shows the on off button which is also working but when I click to get to the thermostat page is showing waiting sinric... And stays there showing the 3 dots for waiting. 

![screenshot_20181217-170710](https://user-images.githubusercontent.com/5132377/50444697-a099b500-0912-11e9-9a5b-6c8328cb98cc.png)

At least a month back it was showing the temperature... An idea what is happening? I already tried removing the thermostat and adding a new one from sinric but the result is the same...

**Comment by emnik** [comment]
Any idea why is this happening? Does it happen to all  or is it only me?

**Comment by The-Great-One** [comment]
> Hi kakopappa!
> The Amazon Alexa app is showing the thermostat sinric device which is working as expected regarding voice commands and responses, it shows the on off button which is also working but when I click to get to the thermostat page is showing waiting sinric... And stays there showing the 3 dots for waiting. At least a month back it was showing the temperature... An idea what is happening? I already tried removing the thermostat and adding a new one from sinric but the result is the same...

Hello emnik, 
                     Could you share the code you used to make the thermostat. I have been trying to use this code but since i have no programming skill i am unable to do so. Thanks!

**Comment by kakopappa** [comment]
@emnik 

Finally got around to checking it. Seems to be fine. Is it still same for you

![ac](https://user-images.githubusercontent.com/7474406/50521090-8ddfd580-0af6-11e9-8045-560a65b801f1.jpg)

**Comment by emnik** [comment]
Nope... Still the same here. If i ask for the thermostat's temperature
Alexa reports the temperature correct but the app is still showing the 3
dots and says waiting for sinric ..

Στις Παρ, 28 Δεκ 2018, 18:16 ο χρήστης Aruna Tennakoon <
notifications@github.com> έγραψε:

**Comment by kakopappa** [comment]
@emnik 
Can you check now, please?. 

Made a few changes and tested in my dev environment again. Is it less than 0 degress where you live now?

**Comment by emnik** [comment]
I'll be away from home till next week... When I'll get back I'll try it.
Happy new year by the way ;-)

Στις Δευ, 31 Δεκ 2018, 15:27 ο χρήστης Aruna Tennakoon <
notifications@github.com> έγραψε:

**Comment by kakopappa** [comment]
Same to you!

**Comment by kakopappa** [comment]
This issue has been a very frustrating one to fix. It used to work then did not. Perhaps it's the same reason why it stopped working for you as well. I think I spent over 6 hours trying to figure out what's wrong.  Response to Alexa is correct but it just refuses to show the updated temperature settings on the app. After few hours of changing the responses to Alexa managed to fix it. It seems Amazon is very picky when it comes to reading temperature when the thermostat is in different modes.

Check again. If it does not work you may have to delete the device and create a new one  @(perhaps changing the name if possible)  Alexa seems to remember the previous settings and seems to mess up sometimes (may be in cache still)

**Comment by emnik** [comment]
Yes now it is working! I indeed needed to delete the device and add a new one with a different name. (I've done that also in the past without success, so the latest changes you did where good! ;-)
