### ISSUE TITLE
alexa cannot link sinric skill

### ISSUE THREAD

**Issue by CabalSoul** [kakopappa/sinric#189]
Hello, as advised I tried to relink Alexa to sinric. I’m trying since yesterday but I cannot link the skill in the alexa App (iOS) anymore. I get, after logging with sinric credentials, that is not possible to link the App at the moment I should try later again.
Is there any solution available?

**Comment by kakopappa** [comment]
Use PC

Goto alexa.amazon.com

**Comment by CabalSoul** [comment]
Thank you, that worked :)
