### ISSUE TITLE
Fan Speed Control causes "Sorry, Ceiling Fan is not responding."

### ISSUE THREAD

**Issue by willmegginson** [kakopappa/sinric#191]
I'm working on connecting my fan to Alexa and am almost done. The only thing that doesn't work 100% is when I change the fan's speed, Alexa says "Sorry, Ceiling Fan is not responding".

Based on looking through similar issues, there might be something wrong with the response that Alexa is getting. 

I can see that the JSON request to my ESP8266 is a SetPercentage action.

I found the Amazon article about SetPercentage, and the expected response. https://developer.amazon.com/docs/device-apis/alexa-percentagecontroller.html#response

Thank you for all that you do. Sinric is a godsend.

**Comment by willmegginson** [comment]
To turn on the fan, I say "Alexa, turn on Ceiling Fan." This sends {"deviceId":"xxxxx","action":"setPowerState","value":"ON"}.

When I say "Alexa, set Ceiling Fan to high." It sends {"deviceId":"5c2bf4bc796c411478dfc368","action":"SetPercentage","value":{"percentage":100}}, and replies "Sorry, Ceiling Fan is not responding."

**Comment by willmegginson** [comment]
It works now! Thanks

**Comment by hemsinghBanoth** [comment]
Hello,
I'm Hemsingh, I request you to incorporate robot movement commands on sinric which includes robot to move all possible 8 directions and turn around, go to specific room, robot to bring water bottle etc. i am planning to purchase the devices as early as possible once confirmation is received from you. 
Thank you.
with regards, Hem, cmsscr@yahoo.com
