### ISSUE TITLE
Error on switch_example2.ino line 65

### ISSUE THREAD

**Issue by satbranigan** [kakopappa/sinric#202]
digitalWrite(relayPin1, LOW); error

digitalWrite(relayPin2, LOW); ok

Thank you so much for the code.

**Comment by AakashKumar21** [comment]
It compiles without error on Arduino IDE 1.8.8 , 
Check if you have required libraries installed. And correct board selected.

**Comment by kakopappa** [comment]
Thanks . fixed.
