### ISSUE TITLE
All my google home can not reach Sinric 

### ISSUE THREAD

**Issue by aryeguetta** [kakopappa/sinric#213]
Hello, I have worked with Sinric on my Google Home mini (two devices) and for an unknown reason it stops working - Every time it say "Sorry, I could not reach Sinric" when I ask to sync - It say that it got an Error while connecting to Sinric, I would be happy to know if that is on my End or Sinric's End.
I am not sure what I should do now?
A couple of days ago we had Error with both Alexa and Google Home - It seems like Alexa is fixed now BUT for Google Sinric is unreachable - Please assist.
Thanks

**Comment by kakopappa** [comment]
Let me check the server status

**Comment by kakopappa** [comment]
No errors on the server. Seems to work fine. here is proof

![image_6483441](https://user-images.githubusercontent.com/7474406/51440583-41557780-1cfb-11e9-829e-a90d0be882f3.JPG)

try disabling and enabling the skill again.

**Comment by shreyamt** [comment]
I faced the same issue and I know the reason: in the Google Home guide, it says you have to "TEST" the skill. The problem is, "TEST" services only last for 30 days on the Google Actions console, after which it stops working. Then I have to unlink the sinroc account from Google, re-deploy the service as a test and then relink the account. Also, I have to set up all the routines again. Is there any way to deploy the service permanently, so this exercise is not required after every 30 days?

**Comment by kakopappa** [comment]
@aryeguetta Last time I checked, They asked me to ship two devices for them to test the hardware and approve it if I want the action in the store.

**Comment by servermcp** [comment]
Can WE($) do that?

**Comment by kakopappa** [comment]
@servermcp bribe an google employee?

**Comment by servermcp** [comment]
Sending you money to print the pcb, buy components and print in 3D a case of, for example, a smart socket. There are many people interested in Sinric with knowledge of electronics that could help with the design of the pcb and those who do not, we collaborate with money! let sinric fly!!

**Comment by Deimos1994** [comment]
@kakopappa, I just curious what have openHAB shipped to Google? as far as I understand they don't make hardware... and there are other projects that aimed at DIYers that get approved, why not Sinric?
What hardware does Google want? a couple of esp8266's?
Maybe you should explain to them that Sinric doesn't make hardware, and that the whole point is to make it yourself.
By the way, I've used python to connect my PC to Sinric (just for testing), and it works, so you can try to offer them a python code instead, so they can test Sinric without any additional hardware.

**Comment by Fleker** [comment]
In order to verify that actions meet policy guidelines, there is a review process. In the domain of smart home, which is based around physical devices, this review process requires a physical certification process. This may include hardware manufactured by a company or whatever hardware and software setup is required for a particular service.

I understand this may be additional overhead for these maker-focused services, and I would be willing to help get to an MVP that can be certified. However, this requirement isn't going to be waved. I can try to see how similar groups such as openHAB did their certification, which could help guide this project forward.

**Comment by kakopappa** [comment]
Thanks.

**Comment by kakopappa** [comment]
Ok so, linking error "401. That’s an error. Your client does not have permission to the requested URL blah blah. That’s all we know. " seem to be related to iOS Safari. Clearing history and website data from iOS Home-> Settings > Safari seems to fix it.  I have updated the guide accordingly.

Next, we have to get the action approved. Let's give some time to Nick to see what he comes up with

**Comment by Fleker** [comment]
All smart home actions need to go through physical certification. This can be shipping a Raspberry Pi with the software to the facility for review, which is what similar DIY platforms have done.

**Comment by qwandor** [comment]
Any news on getting the Google Home integration certified so we don't have to each set up a test account and re-enable it every 30 days? I'm also happy to contribute towards a fund for sending a test device to Google, or even put together an example device with a few LEDs and some decent firmware and send it myself, if that would help.

**Comment by kakopappa** [comment]
Anyone here from US? my problem is shippnig to USA testing ceneter costs me like 60-80$ for a 7$ item which I really do not like... I can buy a ESP module with relay controller and ship it  someone in US is willing to help me out here.

**Comment by al8943** [comment]
@kakopappa, I live in Colorado USA, I would happy to help.

**Comment by al8943** [comment]
I can send this in your behalf, you would just need to send me the information. I am happy to donate it for the project.
  https://www.ebay.com/itm/Mini-Size-ESP8266-Relay-Module-10A-220V-Network-Relay-WIFI-Module-Board-ZP/362546557795?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

I also have a design of my own that I use to drive an RGB strip and water pump on a fountain that I can send in.

**Comment by kakopappa** [comment]
That’s awesome. Thank you.

I can pay for this and ship this to your address if you wish. Do you have
access to a 3d printer? I was thinking may be we need to print a case for
this before sending it so it doesn’t look weird. What do you think?

I have created a channel in Slack #sinric if anyone interested in joining.

Cheers

**Comment by al8943** [comment]
There is no need to send anything, I have a 3d printer and I think I can
put something togherther in the next week, then I wil send you pictures to
see if OK with you.
Cheers
Al.

**Comment by kakopappa** [comment]
Thanks. 

I have resubmitted the google home action again for approval. 

They should get back to me with in cople of days from now. I clearly said Sinric does not manufature hardware and if required we can ship one. Let's see their reponse.

Thanks all

**Comment by kakopappa** [comment]
Here is the progress so far: I will update it as it progress

Project submission - **Done**
Policy review Initiated - **Done**
Submission of Compatible Device Form - **Done**
Policy review passed and email confirmation is sent - Waiting
Completion of Intake Form (to send devices for testing) - Pending
Devices sent for testing and certification (instructions in Policy Email) - Pending
Devices pass testing and your project launches! - Pending

**Comment by al8943** [comment]
If necessary i have this ready to ship.
It incorporates  https://github.com/the-real-orca/WiFiManager, OTA updates
and responds to all google assistant and alexa light actions.
If you want me to send it, I would need to know what you for DeviceID,
APIKey and name for AP SSID and OTA update hostname.
I don't know if I can send the pictures this way, if you don't receive them
give me an email where I can send them.
Al.

**Comment by kakopappa** [comment]
Please drop me an email

aruna.tennakoon@gmail.com

I will send you the API Key and Sinric account login for GH testing

Let me know if you need any help with testing.

**Comment by servermcp** [comment]
Kakopappa, can we make a permanent thread on this topic? To follow it closely

**Comment by tonyshree18** [comment]
For me the Switch is showing in google app but the relay is not turning on. But the same time I checked with alexa it worked. But not with google assistant. I used a different code in arduino and I am using ESP32. Help me

**Comment by kakopappa** [comment]
@tonyshree18 On/Off command format is different in Google Home. Check the google home example code

**Comment by tonyshree18** [comment]
> No errors on the server. Seems to work fine. here is proof
> 
> ![image_6483441](https://user-images.githubusercontent.com/7474406/51440583-41557780-1cfb-11e9-829e-a90d0be882f3.JPG)
> 
> try disabling and enabling the skill again.

I too received the screen like you. But the relay is not switching on. I tried the same with alexa it worked but no with google assistant

**Comment by kakopappa** [comment]
Have you changed your code to support google home?

Notice the difference in action?

https://github.com/kakopappa/sinric/blob/master/arduino_examples/google_home_switch_example.ino


Line 91

**Comment by tonyshree18** [comment]
Then what are the output pin numbers to connect with my relay module??

**Comment by tonyshree18** [comment]
Hello Sir,

            Currently, I am using this code to run my project :

#include <SocketIOclient.h>
#include <WebSockets.h>
#include <WebSockets4WebServer.h>
#include <WebSocketsClient.h>
#include <WebSocketsServer.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WiFiClient.h>
#include <WiFiClientSecure.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>
#include <libb64cencode.h>

#include <Arduino.h>
#include <WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h> //
https://github.com/kakopappa/sinric/wiki/How-to-add-dependency-libraries
#include <ArduinoJson.h> //
https://github.com/kakopappa/sinric/wiki/How-to-add-dependency-libraries
#include <StreamString.h>

#include <AceButton.h> // https://github.com/bxparks/AceButton
using namespace ace_button;
WiFiMulti WiFiMulti;
WebSocketsClient webSocket;
WiFiClient client;

#define MyApiKey "MYAPIKEY" // TODO: Change to your sinric API Key. Your
API Key is displayed on sinric.com dashboard
#define MySSID "SSID" // TODO: Change to your Wifi network SSID
#define MyWifiPassword "PASSWORD" // TODO: Change to your Wifi network
password

#define HEARTBEAT_INTERVAL 300000 // 5 Minutes

uint64_t heartbeatTimestamp = 0;
bool isConnected = false;

// Switch
const int BUTTON1_PIN = 32;
const int BUTTON2_PIN = 35;
const int BUTTON3_PIN = 34;
const int BUTTON4_PIN = 39;


//Relays
const int RELAY1_PIN = 15;
const int RELAY2_PIN = 2;
const int RELAY3_PIN = 4;
const int RELAY4_PIN = 22;

//Status LEDs
const int LED1 = 26;
const int LED2 = 25;
const int LED3 = 27;


String device_ID_1 = "DEVICEID";
String device_ID_2 = "DEVICEID";
String device_ID_3 = "DEVICEID";
String device_ID_4 = "DEVICEID";



ButtonConfig config1;
AceButton button1(&config1);
ButtonConfig config2;
AceButton button2(&config2);
ButtonConfig config3;
AceButton button3(&config3);
ButtonConfig config4;
AceButton button4(&config4);




void handleEvent1(AceButton*, uint8_t, uint8_t);
void handleEvent2(AceButton*, uint8_t, uint8_t);
void handleEvent3(AceButton*, uint8_t, uint8_t);
void handleEvent4(AceButton*, uint8_t, uint8_t);

void setPowerStateOnServer(String deviceId, String value);

// deviceId is the ID assgined to your smart-home-device in sinric.com
dashboard. Copy it from dashboard and paste it here

void turnOn(String deviceId) {
  if (deviceId == device_ID_1) // Device ID of first device
  {
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(RELAY1_PIN, LOW);
  }
  if (deviceId == device_ID_2) // Device ID of first device
  {
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(RELAY2_PIN, LOW);
  }
  if (deviceId == device_ID_3) // Device ID of first device
  {
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(RELAY3_PIN, LOW);
  }
  if (deviceId == device_ID_4) // Device ID of first device
  {
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(RELAY4_PIN, LOW);
  }

}

void turnOff(String deviceId) {
  if (deviceId == device_ID_1) // Device ID of first device
  {
    Serial.print("Turn off Device ID: ");
    Serial.println(deviceId);
    digitalWrite(RELAY1_PIN, HIGH);
  }
  if (deviceId == device_ID_2) // Device ID of first device
  {
    Serial.print("Turn off Device ID: ");
    Serial.println(deviceId);
    digitalWrite(RELAY2_PIN, HIGH);
  }
  if (deviceId == device_ID_3) // Device ID of first device
  {
    Serial.print("Turn off Device ID: ");
    Serial.println(deviceId);
    digitalWrite(RELAY3_PIN, HIGH);
  }
  if (deviceId == device_ID_4) // Device ID of first device
  {
    Serial.print("Turn off Device ID: ");
    Serial.println(deviceId);
    digitalWrite(RELAY4_PIN, HIGH);
  }

}

void webSocketEvent(WStype_t type, uint8_t * payload, size_t length) {
  switch (type) {
    case WStype_DISCONNECTED:
      isConnected = false;
      WiFiMulti.addAP(MySSID, MyWifiPassword);
      Serial.printf("[WSc] Webservice disconnected from sinric.com!\n");
      break;
    case WStype_CONNECTED: {
        isConnected = true;
        Serial.printf("[WSc] Service connected to sinric.com at url: %s\n",
payload);
        Serial.printf("Waiting for commands from sinric.com ...\n");
      }
      break;
    case WStype_TEXT: {
        Serial.printf("[WSc] get text: %s\n", payload);
        // Example payloads

        // For Switch or Light device types
        // {"deviceId": xxxx, "action": "setPowerState", value: "ON"} //
https://developer.amazon.com/docs/device-apis/alexa-powercontroller.html

        // For Light device type
        // Look at the light example in github

#if ARDUINOJSON_VERSION_MAJOR == 5
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject((char*)payload);
#endif
#if ARDUINOJSON_VERSION_MAJOR == 6
        DynamicJsonDocument json(1024);
        deserializeJson(json, (char*) payload);
#endif
        String deviceId = json ["deviceId"];
        String action = json ["action"];

        if (action == "setPowerState") { // Switch or Light
          String value = json ["value"];
          if (value == "ON") {
            turnOn(deviceId);
          } else {
            turnOff(deviceId);
          }
        }
        else if (action == "test") {
          Serial.println("[WSc] received test command from sinric.com");
        }
      }
      break;
    case WStype_BIN:
      Serial.printf("[WSc] get binary length: %u\n", length);
      break;
  }
}

void setup() {
  Serial.begin(9600);

  WiFiMulti.addAP(MySSID, MyWifiPassword);
  Serial.println();
  Serial.print("Connecting to Wifi: ");
  Serial.println(MySSID);

  // Waiting for Wifi connect
  if (WiFiMulti.run() != WL_CONNECTED) {
    delay(500);
    Serial.print("Connecting...");
  }
  if (WiFiMulti.run() == WL_CONNECTED) {
    Serial.println("");
    Serial.print("WiFi connected. ");
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
  }

  // Setup button
  // Button uses the built-in pull up register.
  pinMode(BUTTON1_PIN, INPUT_PULLUP); // INPUT_PULLUP so no need a 10K
resistor
  pinMode(BUTTON2_PIN, INPUT_PULLUP); // INPUT_PULLUP so no need a 10K
resistor
  pinMode(BUTTON3_PIN, INPUT_PULLUP); // INPUT_PULLUP so no need a 10K
resistor
  pinMode(BUTTON4_PIN, INPUT_PULLUP); // INPUT_PULLUP so no need a 10K
resistor

  pinMode(RELAY1_PIN, OUTPUT);
  pinMode(RELAY2_PIN, OUTPUT);
  pinMode(RELAY3_PIN, OUTPUT);
  pinMode(RELAY4_PIN, OUTPUT);

   pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);

  digitalWrite(LED1, HIGH);
  delay(200);
  digitalWrite(LED2, HIGH);
  delay(200);
  digitalWrite(LED3, HIGH);
  delay(200);

  digitalWrite(LED1, LOW);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, LOW);
  delay(500);

  digitalWrite(LED1, HIGH);
  delay(200);
  digitalWrite(LED2, HIGH);
  delay(200);
  digitalWrite(LED3, HIGH);
  delay(200);

  digitalWrite(LED1, LOW);
  digitalWrite(LED2, LOW);
  digitalWrite(LED3, LOW);


  config1.setEventHandler(button1Handler);
  config2.setEventHandler(button2Handler);
  config3.setEventHandler(button3Handler);
  config4.setEventHandler(button4Handler);


  button1.init(BUTTON1_PIN);
  button2.init(BUTTON2_PIN);
  button3.init(BUTTON3_PIN);
  button4.init(BUTTON4_PIN);



  // server address, port and URL
  webSocket.begin("iot.sinric.com", 80, "/");

  // event handler
  webSocket.onEvent(webSocketEvent);
  webSocket.setAuthorization("apikey", MyApiKey);

  // try again every 5000ms if connection has failed
  webSocket.setReconnectInterval(5000);   // If you see 'class
WebSocketsClient' has no member named 'setReconnectInterval' error update
arduinoWebSockets
}

void loop() {

  if (WiFiMulti.run() != WL_CONNECTED)
  {
    Serial.println("Not Connected");
    digitalWrite(LED1, HIGH);
    digitalWrite(LED2, LOW);
    digitalWrite(LED3, LOW);
  }
  else
  {
    Serial.println(" Connected");
    digitalWrite(LED1, HIGH);
    digitalWrite(LED2, HIGH);
    digitalWrite(LED3, HIGH);
    webSocket.loop();
  }


  button1.check();
  button2.check();
  button3.check();
  button4.check();


  if (isConnected) {
    uint64_t now = millis();

    // Send heartbeat in order to avoid disconnections during ISP resetting
IPs over night. Thanks @MacSass
    if ((now - heartbeatTimestamp) > HEARTBEAT_INTERVAL) {
      heartbeatTimestamp = now;
      webSocket.sendTXT("H");
    }
  }
}

void setPowerStateOnServer(String deviceId, String value) {
#if ARDUINOJSON_VERSION_MAJOR == 5
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.createObject();
#endif
#if ARDUINOJSON_VERSION_MAJOR == 6
  DynamicJsonDocument root(1024);
#endif

  root["deviceId"] = deviceId;
  root["action"] = "setPowerState";
  root["value"] = value;
  StreamString databuf;
#if ARDUINOJSON_VERSION_MAJOR == 5
  root.printTo(databuf);
#endif
#if ARDUINOJSON_VERSION_MAJOR == 6
  serializeJson(root, databuf);
#endif
  webSocket.sendTXT(databuf);
}

void button1Handler(AceButton* button, uint8_t eventType, uint8_t
buttonState) {
  Serial.println("EVENT1");
  switch (eventType) {
    case AceButton::kEventPressed:
      Serial.println("kEventPressed");
      setPowerStateOnServer(device_ID_1, "ON");
      digitalWrite(RELAY1_PIN, LOW);
      break;
    case AceButton::kEventReleased:
      Serial.println("kEventReleased");
      setPowerStateOnServer(device_ID_1, "OFF");
      digitalWrite(RELAY1_PIN, HIGH);
      break;
  }
}

void button2Handler(AceButton* button, uint8_t eventType, uint8_t
buttonState) {
  Serial.println("EVENT2");
  switch (eventType) {
    case AceButton::kEventPressed:
      Serial.println("kEventPressed");
      setPowerStateOnServer(device_ID_2, "ON");
      digitalWrite(RELAY2_PIN, LOW);
      break;
    case AceButton::kEventReleased:
      Serial.println("kEventReleased");
      setPowerStateOnServer(device_ID_2, "OFF");
      digitalWrite(RELAY2_PIN, HIGH);
      break;
  }
}

void button3Handler(AceButton* button, uint8_t eventType, uint8_t
buttonState) {
  Serial.println("EVENT3");
  switch (eventType) {
    case AceButton::kEventPressed:
      Serial.println("kEventPressed");
      setPowerStateOnServer(device_ID_3, "ON");
      digitalWrite(RELAY3_PIN, LOW);
      break;
    case AceButton::kEventReleased:
      Serial.println("kEventReleased");
      setPowerStateOnServer(device_ID_3, "OFF");
      digitalWrite(RELAY3_PIN, HIGH);
      break;
  }
}

void button4Handler(AceButton* button, uint8_t eventType, uint8_t
buttonState) {
  Serial.println("EVENT4");
  switch (eventType) {
    case AceButton::kEventPressed:
      Serial.println("kEventPressed");
      setPowerStateOnServer(device_ID_4, "ON");
      digitalWrite(RELAY4_PIN, LOW);
      break;
    case AceButton::kEventReleased:
      Serial.println("kEventReleased");
      setPowerStateOnServer(device_ID_4, "OFF");
      digitalWrite(RELAY4_PIN, HIGH);
      break;
  }
}


This code is perfectly running with my Alexa, but not with Google
Assistant. You have shared me a screenshot on which the light works. The
same screen appeared to me. No errors in Google Assistant, I have
successfully linked my sinric account and added my devices. Then I tested
to turn on the relay. It shows that the relay is turned on, but the relay
didn't. But, With Alexa the relay turned on. I am using ESP32 WiFi
Development Board. The pin of First relay is 15 and second is 2, third is 4
and fourth is 22. Please help me connecting. In your code what are the pin
numbers that I needed to connect? Please tell me

**Comment by kakopappa** [comment]
@tonyshree18  

Google Home / Alexa has a different command format. first test using this Google Home sketch whether Google Home works.
https://github.com/kakopappa/sinric/blob/master/arduino_examples/google_home_switch_example.ino#L91

Second.
Change this line if (action == "setPowerState") to if (action == "setPowerState" || action == "action.devices.commands.OnOff")

**Comment by tonyshree18** [comment]
Okay I asked you what are the pin numbers writen in the code?? To connect
with my relay module?

**Comment by tonyshree18** [comment]
This is the error message I got from Arduino IDE while compiling :

Arduino: 1.8.13 (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 921600,
None"


In file included from
C:\Users\tonys\OneDrive\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:33:0,

                 from
C:\Users\tonys\OneDrive\Desktop\Google_Assistant_Home_Automation_using_Sinric\Google_Assistant_Home_Automation_using_Sinric.ino:6:

C:\Users\tonys\OneDrive\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiType.h:26:19:
fatal error: queue.h: No such file or directory

compilation terminated.

exit status 1

Error compiling for board DOIT ESP32 DEVKIT V1.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


Please help me, I am getting many errors

**Comment by kakopappa** [comment]
@tonyshree18 Sketch is written for Esp8266, you are compiling it on Esp32. 

If you have a further question open another issue

**Comment by tonyshree18** [comment]
Hi, I uploaded the sketch. What are the pins that I need to connect. please tell me. I don't find any pin numbers in the sketch
