### ISSUE TITLE
No Value payload in"SetColorTemperture"

### ISSUE THREAD

**Issue by PSUGuy** [kakopappa/sinric#22]
When I tell Alexa (using the app) to set the color temperature (not increase/decrease), there is no Value payload, has this gone?
when I ask alexa, it  (she?) tells me my value is out of range.

Excellent Work on this project by the way!

**Comment by kakopappa** [comment]
Hello,  Thanks for reporting this issue. I will take a look and update the issue again when it's fixed

**Comment by kakopappa** [comment]
@PSUGuy I checked the code and value parameter was missing in the payload. I fixed it and updated the server. Please check now. 

value is an integer ranging from 1000 to 10000, other than that, Alexa will tell you it's out of range.

 https://developer.amazon.com/docs/device-apis/alexa-colortemperaturecontroller.html

**Comment by PSUGuy** [comment]
@kakopappa Looks like that Fixed it. Thanks.
Interestingly I can tell Alex to set to a shade of white (E.g. "warm white") but I cant say "set color temperature to 3000". I just get a value out of range response.

I'm guessing this is a limitation of the Alexa API

**Comment by kakopappa** [comment]
i will close this issue now
