### ISSUE TITLE
Ligths without brightness control

### ISSUE THREAD

**Issue by juandrueda** [kakopappa/sinric#220]
I have a simple light bulb, i didn't need brightness control in Google Home application... 
only on and off

**Comment by servermcp** [comment]
This example maybe work for you.

https://github.com/kakopappa/sinric/blob/master/arduino_examples/switch_example.ino

**Comment by juandrueda** [comment]
but Google Home application no detect this as lights... detect as switch... if no is possible it's okay

**Comment by servermcp** [comment]
then use the example of lights and only the function of turning on and off will work or zero and 100% will turn off or turn on respectively

**Comment by juandrueda** [comment]
Ok thanks
