### ISSUE TITLE
sinric down ?

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#222]
@kakopappa 
Sinric App.

**Comment by pico563** [comment]
![screenshot_20190204-075845](https://user-images.githubusercontent.com/24532917/52192521-26cee280-2853-11e9-984b-ebca7ea638f9.png)

**Comment by kakopappa** [comment]
I think server crashed and restarted. Seems to be ok now

**Comment by pico563** [comment]
### Sinric still down

**Comment by kakopappa** [comment]
I am at work. I will check when I get back in few hours sorry about the
delay

**Comment by pico563** [comment]
Thank you @kakopappa 
sorry for that
take you time, nothing hurry.
thanks again

**Comment by kakopappa** [comment]
sorry buddy app, alexa and server seems fine. is it still same? check the blocked ips ?

**Comment by kakopappa** [comment]
all good now?

**Comment by pico563** [comment]
YES.
But please check I am still on 197.161.130.xxx  
is there any problem from my site.
