### ISSUE TITLE
Turn on light by code

### ISSUE THREAD

**Issue by CptZeroG** [kakopappa/sinric#226]
Hi y'all,
I would to know if is possible to call an action, for example light up a LED (registered on SINRIC), from another board like NodeMCU.

The scenario is:
1) nodeMCU registered under SINRIC (connected via Skill to ALEXA), with a LED strip.
2) another nodeMCU with a button.

I'd like to turn on the LED strip using SINRIC (and, obviusly, then change the LED status),by pressing on the button of the second NMCU.

Can someone help me? Aruna?

**Comment by kakopappa** [comment]
Send a UDP command from one to another?

**Comment by CptZeroG** [comment]
Do you mean without pass trough the SINRIC server, send and receive command from and to NMCU and then change the state on SINRIC server? 
mhmm ... Maybe it's a solution, but works only if all the devices is under the same network.

It's no possible to send commands to SINRIC as, i suppose, the ALEXA server does?

**Comment by kakopappa** [comment]
sinric does not support this. it just  relay commands from alexa to your esp module. look for a public mqtt server

**Comment by CptZeroG** [comment]
Ok, all clear.
UDP connections or MQTT server.

Thanks Aruna.
