### ISSUE TITLE
Sinric on nodemcu

### ISSUE THREAD

**Issue by steve8266** [kakopappa/sinric#227]
Hi, first github post hope in right place. Have loaded the github Sinric switch example onto nodemcu and it works fine. Can turn on and off via Alexa device (switch). But Alexa still allows on/off even when nodemcu is turned off, I.e should be unresponsive. What am I doing wrong please?

**Comment by kakopappa** [comment]
hi @steve8266 welcome to Sinric world. 

This is a work-around I have implemented to get the Amazon Skill passed (Japanese) once it's done I will fix this back.

**Comment by steve8266** [comment]
Many thanks. Sorry but I don’t fully understand. Are you saying you can provide a fix in near future?? Regards, Steve

**Comment by nilava** [comment]
He meant that when skills are submitted for checking in alexa skill store, devices must be online for the test team to check, so he changed the if the devices can send its state back to server to off, so every device is online all the time!

**Comment by steve8266** [comment]
Ah, now I understand. Thanks Nilava. Actually I've found the sinric devices rock solid thus far anyway and much more stable that the faux stuff I've tried in the past. So the lack of 'device can send state back' is not the big issue I thought it would be when I made the initial comment. Regards, Steve
