### ISSUE TITLE
How can I add 8 relay?

### ISSUE THREAD

**Issue by canuri** [kakopappa/sinric#230]
Hi how can i add more device?
I saw only two device in example code.
`void turnOn(String deviceId) {
  if (deviceId == "5c7282***************084") // Device ID of first device
  {  
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(2, HIGH);
  } 
  else if (deviceId == "5c728b6b************42420") // Device ID of second device
  { 
    Serial.print("Turn on device id: ");
    Serial.println(deviceId);
    digitalWrite(3, HIGH);
  }
  else {
    Serial.print("Turn on for unknown device id: ");
    Serial.println(deviceId);
    
  }     
}`

**Comment by kakopappa** [comment]
you can extend the if condition like this


`
void turnOn(String deviceId) {
	if (deviceId == "5c7282***************084") // Device ID of first device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		digitalWrite(2, HIGH);
	}
	else if (deviceId == "5c728b6b************42420") // Device ID of second device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		digitalWrite(3, HIGH);
	}
	else if (deviceId == "xxxxx") // Device ID of second device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		
	}
	else if (deviceId == "xxxxx") // Device ID of second device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		
	}
	else if (deviceId == "xxxxx") // Device ID of second device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		
	}
	else if (deviceId == "xxxxx") // Device ID of second device
	{
		Serial.print("Turn on device id: ");
		Serial.println(deviceId);
		
	}
	else {
		Serial.print("Turn on for unknown device id: ");
		Serial.println(deviceId);

	}
}
`

**Comment by canuri** [comment]
> you can extend the if condition like this
> 
> `
> void turnOn(String deviceId) {
> if (deviceId == "5c7282***************084") // Device ID of first device
> {
> Serial.print("Turn on device id: ");
> Serial.println(deviceId);
> digitalWrite(2, HIGH);
> }
> else if (deviceId == "5c728b6b************42420") // Device ID of second device
> {
> Serial.print("Turn on device id: ");
> Serial.println(deviceId);
> digitalWrite(3, HIGH);
> }
> else if (deviceId == "xxxxx") // Device ID of second device
> {
> Serial.print("Turn on device id: ");
> Serial.println(deviceId);
> 
> ```
> }
> else if (deviceId == "xxxxx") // Device ID of second device
> {
> 	Serial.print("Turn on device id: ");
> 	Serial.println(deviceId);
> 	
> }
> else if (deviceId == "xxxxx") // Device ID of second device
> {
> 	Serial.print("Turn on device id: ");
> 	Serial.println(deviceId);
> 	
> }
> else if (deviceId == "xxxxx") // Device ID of second device
> {
> 	Serial.print("Turn on device id: ");
> 	Serial.println(deviceId);
> 	
> }
> else {
> 	Serial.print("Turn on for unknown device id: ");
> 	Serial.println(deviceId);
> 
> }
> ```
> }
> `

thank you

**Comment by canuri** [comment]
my problem solved
