### ISSUE TITLE
 ("Turn on unknown device id:");

### ISSUE THREAD

**Issue by mascolo74** [kakopappa/sinric#233]
Sorry for my English,
alexa responds to the commands but on the serial at each command appears the writing:
Serial.print ("Turn on unknown device id:");
  Serial.println (deviceId);
that is, it does not recognize me as a switch and therefore it gives me an unknown switch

**Comment by mascolo74** [comment]
void turnOn(String deviceId) {
 if (deviceId == "5cxxxxxxxxxxxxxxxa") // Device ID of device 1
 { 
 Serial.print("Turn on device id: ");
 Serial.println(deviceId);
  digitalWrite(device1,HIGH);
  delay(500);
  digitalWrite(device1,LOW);
 } 
 else if (deviceId == "5cxxxxxxxxb") // Device ID of device 2
 { 
 Serial.print("Turn on device id: ");
 Serial.println(deviceId);
 digitalWrite(device2,HIGH);
 delay(500);
 digitalWrite(device2,LOW);
 }
 else if (deviceId == "5cxxxxc") // Device ID of device 3
 { 
 Serial.print("Turn on device id: ");
 Serial.println(deviceId);
 digitalWrite(device3,HIGH);
 delay(500);
 digitalWrite(device3,LOW);
 } 
 else if (deviceId == "5cxxxxd") // Device ID of device 4
 { 
 Serial.print("Turn on device id: ");
 Serial.println(deviceId);
 digitalWrite(device4,HIGH);
 delay(500);
 digitalWrite(device4,LOW);
 }
 
 else 
 {
 Serial.print("Turn on unknown device id: ");
 Serial.println(deviceId); 
 }

**Comment by kakopappa** [comment]
looks like your device id is missing in the if statement. 

check the 
if (deviceId == "5cxxxxd") <---- This should be same as your device id in the dashboard

**Comment by mascolo74** [comment]
I rewrote the code 4 times but keep doing the same thing .......... I have 4 pins and the four codes are correct

**Comment by kakopappa** [comment]
If you are seeing "Turn on unknown device id: " in the serial terminal, it's likely your device id not in the if else statement. If you can post your code here without the API key i can take a look

**Comment by mascolo74** [comment]
I did a complete reset of alexa by removing all the devices, turned off and on alexa and now it works thanks a lot

**Comment by mascolo74** [comment]
now I try to make it work with buttons
