### ISSUE TITLE
Google home TV

### ISSUE THREAD

**Issue by big-data-elg** [kakopappa/sinric#236]
I created a TV device for google home. However, google assistant recognized it as an outlet.
But alexa recognized it as a TV.

**Comment by Deimos1994** [comment]
That is because Google doesn't support TV
https://developers.google.com/actions/smarthome/guides/

**Comment by servermcp** [comment]
What TV device did you create?

**Comment by big-data-elg** [comment]
Thank you for your replies. 
@servermcp I created a TV device on sinric site. and i made a device with EPS8266 and IR Led. 
alexa was working good. But google home was working just power On/Off.

**Comment by servermcp** [comment]
Cool! I was thinking about doing one but I use GH and it does not support TV! :(
