### ISSUE TITLE
Sinric Down?

### ISSUE THREAD

**Issue by senic35** [kakopappa/sinric#24]
Is Sinric down? I cant login to my account anymore.. it always comes up with `User not found` . I can create a new account but the problem persists. Any info on this?

**Comment by senic35** [comment]
Alright i took a different E-Mail and it worked. I was able to create a new account with the same E-Mail I used before tho. Also saw issue #7

**Comment by kakopappa** [comment]
There was a problem related to username being case-sentive and I fixed it and forsome reason issue still persists. 

Please use lowercase email address when you sign-up if you have still have any issues

https://github.com/kakopappa/sinric/issues/23

**Comment by kakopappa** [comment]
@senic35 
I will close this issue since #23 is fixed. now. 

Let me know if you still have any issues
