### ISSUE TITLE
increase/decrease volume on TV

### ISSUE THREAD

**Issue by Mahmoud-AlQarout** [kakopappa/sinric#243]
How can I increase/decrease volume using IR transmitter?
Because  "void adjustVolume" give me only one action !

**Comment by kakopappa** [comment]
you have to keep the current volume in the memory and adjust it when you receive the command. 

new = current + adjustVolume;

**Comment by Mahmoud-AlQarout** [comment]
Thanks for reply 

But I want to send ir code using
Irsend.sendNEC
That will increase the volume
And other one to decrease volume

Because I can't embed together, it will send one of them.

Thanks in advance !

**Comment by Mahmoud-AlQarout** [comment]
I solved it .

I used -10 as a value and it's work

            `else if(action == "AdjustVolume") { 
            
            const char* kcvolume = json ["value"]["volume"];
            int volume = atoi(kcvolume);  
            adjustVolume(volume); 

            if (volume == -10){
            irsend.sendNEC(0x718EE21D);
            delay(500);
            irsend.sendNEC(0x718EE21D);
             }
            else {
            irsend.sendNEC(0x718EE01F);
            delay(500);
            irsend.sendNEC(0x718EE01F);
            }
          }`
