### ISSUE TITLE
Code help

### ISSUE THREAD

**Issue by Dan-Asp** [kakopappa/sinric#25]
Hello All, I'm Dan. I am fairly new to coding but have a little experience with arduino. I have managed to add code to the sinric multi switch example and control 4 relays. What i would like to do is build a central heating thermostat using sinric. Any help with the code or even just a push in the right direction would be really helpful. Sorry this is not an issue with sinric and just an issue with my lack of coding experience.

**Comment by kakopappa** [comment]
@Dan-Asp I will upload a example when it's ready.

**Comment by kakopappa** [comment]
@Dan-Asp here you go

https://github.com/kakopappa/sinric/blob/master/arduino_examples/thermostat_example.ino

**Comment by Dan-Asp** [comment]
@kakopappa You are an international superstar!!!

**Comment by kakopappa** [comment]
no you are. thanks for the donation

**Comment by Synco22** [comment]
Hello,

I was looking for such project, thank you very much. I can't find the type of thermal sensor and where to connect it. Can you please tell me?

Best regards,
Keep up the good work,
Bye
