### ISSUE TITLE
alexa no encuentra los dispositivos

### ISSUE THREAD

**Issue by Eugeniobcn** [kakopappa/sinric#261]
alexa no reconoce  los dispositivos de sinric, quite  y añadi de nuevo la skill  sigue sin funcionar, 
Ayer funcionaba correctamente 
gracias

**Comment by kakopappa** [comment]
the server is working fine. 

1. Make sure to enter the device description when you create a device.
2. Unlink and link again

**Comment by Eugeniobcn** [comment]
gracias por tus rápidas respuestas, 
Al borrar los dispositivos ya me reconoce los nuevos, gracias de nuevo,
