### ISSUE TITLE
Help with Sirinc Switch Example 

### ISSUE THREAD

**Issue by Wanganator414** [kakopappa/sinric#267]
Hello, I am currently trying to control a servo using NodeMcu (Cp210x model) with Amazon Alexa. I am working with the Arduino switch example in the Sinric master folder. I have followed instructions so far to install the non-beta versions of ArduinoJson but ran into a roadblock with the WebSocketsClient.h library. I downloaded the zip files suggested in the example and got the lib ArduinoWebSockets, which is a different lib than the one in the example (WebSocketsClient.h). I am now unsure how to proceed after this step. Any guidance would be appreciated, please let me know if any additional information is needed to clarify the issue (First time posting an issue).

Thanks.

**Comment by Dhanush4444** [comment]
@Wanganator414 Try downloading ArduinoJSON of version 5.12.+ from [here](https://www.arduinolibraries.info/libraries/arduino-json). And also try lowering the version of WebSocketClient. [websocket](https://www.arduinolibraries.info/libraries/web-sockets)

**Comment by Wanganator414** [comment]
Hello Dazz, thanks for the info. Lowering WebSocketClient version worked for me.
