### ISSUE TITLE
Google Home + Alexa in same program, same ESP8266

### ISSUE THREAD

**Issue by temocastro** [kakopappa/sinric#277]
Hello,

I have one Alexa-ESP8266 and one GoogleHome-ESP8266, I would like to have both in the board/program, I notice they look basically the same, I just can't make it work,

Any idea/help you can provide? an example?

Thanks

**Comment by dazzHere** [comment]
@temocastro You want both features in same board/program?

**Comment by temocastro** [comment]
yes, same as any WEMO or TP-LINK device that respond to any alexa or google home, same device, 2 different inputs (alexa or google home)

**Comment by dazzHere** [comment]
Unfortunately we cannot do that! Because as it's a websocket sever, you authorize to server using a single API at once. You cannot use 2 API to authorize from single instance.

**Comment by temocastro** [comment]
I would guess same API, you will connect to Sinric momentary for change the state, correct?

**Comment by dazzHere** [comment]
Mail me your code let me check. dhanushdazz@gmail.com

**Comment by temocastro** [comment]
done

**Comment by temocastro** [comment]
Success, I was able to control my single ESP8266 with Google and Alexa

Just the payload needs to change, so I modified the Google Home sketch and added the Alexa payload condition for "Action"

Like this

....
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject((char*)payload); 
        String deviceId = json ["deviceId"];     
        String action = json ["action"];
        
        if(action == "action.devices.commands.OnOff") { // Switch 
            String value = json ["value"]["on"];
            Serial.println(value); 
            
            if(value == "true") {
                turnOn(deviceId);
            } else {
                turnOff(deviceId);
            }
        }
        **else if (action == "setPowerState") { // Switch or Light
            String value = json ["value"];
            if(value == "ON") {
                turnOn(deviceId);
            } else {
                turnOff(deviceId);
            }
        }**
        else if (action == "test") {
            Serial.println("[WSc] received test command from sinric.com");
        }
      }
      break;
....

**Comment by temocastro** [comment]
I will leave this open few days, in cased you have questions, I would like to upload the example, so everybody can use it in the future

@kakopappa take a look, let me know if this makes sense

**Comment by kakopappa** [comment]
yep. looks correct.
