### ISSUE TITLE
I am having to reset my esp8266 devices every few days.

### ISSUE THREAD

**Issue by schaffertown** [kakopappa/sinric#278]
My esp8266s become unresponsive and I have to reset them. I have 2 of them. If I reset one only when they are both working it will work and the other will be first to fail. If I reset both at the same time they usually fail at the same time. It seems to be related to power cycling my modem and router. What do you think is the problem? What affect would changing the heartbeat have? Would a watchdog timer help? 
Thank you for a wonderful service you have provided.

**Comment by kakopappa** [comment]
are you using Google Home or Alexa?

**Comment by schaffertown** [comment]
Alexa
