### ISSUE TITLE
Everything on Google Home is not responding

### ISSUE THREAD

**Issue by maciak** [kakopappa/sinric#299]
Hi,
All of my devices stopped responding for google home app. Is there an issue now? It started happening few days ago.

**Comment by kakopappa** [comment]
https://developers.google.com/actions/tools/simulator

Your Action is testable for up to 30 days. After 30 days, you have to reupload the Action package for testing.

try unlinking and relinking the action. I tried subitting the action for approval but google testing center rejected it. Will try a fresh approch with Sinric Pro again when ready

**Comment by maciak** [comment]
That helped  :) Thank you!
