### ISSUE TITLE
Sinric.com not showing my info

### ISSUE THREAD

**Issue by mrlightsman** [kakopappa/sinric#30]
@kakopappa 
I noticed yesterday when I log into sinric.com my devices are not there and the API is not mine.  However, it welcomes me by name and all of my previously installed devices continue to work with alexa as expected.  Thanks.

**Comment by kakopappa** [comment]
Did you have another account with the same email address (upper case/
lowecas) differently

**Comment by mrlightsman** [comment]
No. Just the one account. Set up about a week ago. 

Jim

**Comment by kakopappa** [comment]
Strange. Can you send me your username

**Comment by mrlightsman** [comment]
Yes. Is there a way to private message so I am not sharing with everyone?

Jim

**Comment by kakopappa** [comment]
Send it to aruna.tennakoon@gmail.com

Cheers

**Comment by BoriKing** [comment]
@kakopappa 

for some reason after you fixed the email issue, the sinric skill was still recognizing the account that was deleted on sinric.com, to fix that i had to disable and re-enable the skill.

**Comment by kakopappa** [comment]
@mrlightsman problem was you have registered for two accounts. 

1. jim@xxxx.com
2. Jim@xxxx.com

With the new update, it's doing a case-insensitve checking when it's looking for your email. Let me know which one you DO NOT USE. i will remove it.

**Comment by mrlightsman** [comment]
Using either Jim or jim both take me to an account with only "Office Light" in it.  This is the wrong account.  I need access to the account that has 8-10 devices in it.  Thank you.

**Comment by kakopappa** [comment]
@mrlightsman that is stragne. 

Can you email me a device id or the previous api key that you used to have? i will look it up on the database.
