### ISSUE TITLE
Missing required parameter

### ISSUE THREAD

**Issue by Megalopole** [kakopappa/sinric#305]
I am configuring access to Google home and displays the following error.
![SmartSelect_20190706-175728_Chrome](https://user-images.githubusercontent.com/42890257/60761097-35930e80-a018-11e9-8f32-65020bd2c2e0.jpg)

**Comment by kakopappa** [comment]
looks like required parameters are not passed from Google when linking. 
https://google.sinric.com/login appears to be working. 

try again and let me know.

**Comment by Megalopole** [comment]
Ok.
