### ISSUE TITLE
Sinric Skill is Not Working 

### ISSUE THREAD

**Issue by B749DF** [kakopappa/sinric#308]
Sinric Skill is Not Working All Devices Are Unresponsive

**Comment by kakopappa** [comment]
Yeah there is a ssl issue. Will fix it soon

**Comment by Travio** [comment]
Guess I should have bought you that beer! :-)

I did try (my wife changed pw and does not remember). I can't even seem to log into my account now. It's gone intermittent. Every now and then it will find my device.

This thing has been super stable from day one. Good luck on getting the SSL fixed quickly.

**Comment by amitabh-srivastav** [comment]
The issue is already fixed. Pl. treat it as closed. : )
Hope this won't happen again, as my home water supply pumps rely on Sinric.

**Comment by kakopappa** [comment]
Always have a button to control
