### ISSUE TITLE
can't access Sinric.com

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#309]
I can't access Sinric.com

`Response with status: 500 OK for URL: https://sinric.com/api/v1/login`

**Comment by kakopappa** [comment]
Thanks for letting me know.

I will fix this ASAP

**Comment by pico563** [comment]
thank you
regards

**Comment by pico563** [comment]
I am trying to re-link Sinric but i get this error

![](https://dl3.pushbulletusercontent.com/I5wqskigMkS1y53m77P0RErTcw43pWep/20190714_044635.png)

**Comment by kakopappa** [comment]
There is an issue related to people sending invalid data and crashing the
server. Working on a fix now.
