### ISSUE TITLE
android app with sinric

### ISSUE THREAD

**Issue by altafc22** [kakopappa/sinric#324]
Hello brother, first of all i appreciate to your work, i'm creating my own android app and i want to connect sinric with my application, can you please tell me how to do this

**Comment by kakopappa** [comment]
@altafc22 Thanks. 

API support for Sinric is limited. (due to people started to abuse them in the beginning)
https://github.com/kakopappa/sinric/wiki

I am planing fix these issues in upcoming Sinric Pro. It will have the proper rate-limit features and API interfaces to build your own app.

**Comment by altafc22** [comment]
thanks : ) 👍
