### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by ilkayefe** [kakopappa/sinric#366]
Closed, you can remove this issue.

**Comment by kakopappa** [comment]
can you post your sketch here without the API key?

**Comment by kakopappa** [comment]
If you have issues reading values from DHT sensor, then i like to recommend you to create a simple sketch to do that and make sure it works first, then you can integrate that code to GH sketch

**Comment by ilkayefe** [comment]
> If you have issues reading values from DHT sensor, then i like to recommend you to create a simple sketch to do that and make sure it works first, then you can integrate that code to GH sketch

I tried example of "DHTesp" library, that worked. Im using this code -> https://github.com/kakopappa/sinric/blob/master/arduino_examples/thermostat_example_with_dht_11.ino

**Comment by ilkayefe** [comment]
How i can fix this issue?

**Comment by murilobaliego** [comment]
Hi @kakopappa, how can I send the temperature value that I get on my DHT sensor to GH server? I tried to send for instance the value "33.3" like below but it did not worked.
[WSc] sendTXT: {"deviceId":"5ec40b1fef8d6c2a9102cd11","action":"action.devices.commands.ThermostatTemperatureAmbient","value":{"thermostatTemperatureAmbient":{"value":"33.3"}}}

Am I using the wrong action commad?
Thanks in advance!! I'm looking forward to use GH in sinric PRO :) congrats for this great work on sinric!!
