### ISSUE TITLE
please help running Sinric on Raspberry pi

### ISSUE THREAD

**Issue by malvar0929** [kakopappa/sinric#37]
Hi Kakopappa, could you please provide me with some quick basic steps on how I can get Sinric running on a raspberry pi. I got it working great on arduino but I'm confused on Raspberry Pi.
I see the node-js sample ( I already have nodejs on the Pi) but I'm not understanding how to control the gpio pins on the pi with Alexa. 
I'm very excited in getting sinric to run.
Thanks in advance.

**Comment by emnik** [comment]
The node.js example is sample code to link node.js with sinric as we do
with arduino, wemos etc. To control the gpio pins you have to implement
your own node.js application that would control a relay or something. To
access the gpio pins you need a node.js module like  pi-gpio: (
https://github.com/rakeshpai/pi-gpio). There are others too so google it!

2018-03-03 21:29 GMT+02:00 malvar0929 <notifications@github.com>:

**Comment by malvar0929** [comment]
Thank you all for the replies. This should enough to get me started. I really love how well it works with Arduino.
