### ISSUE TITLE
Alexa is not discovering

### ISSUE THREAD

**Issue by rpinoncely** [kakopappa/sinric#390]
Hi, I did everything like instructed but Alexa is not discovering my device.

Device is conected to Sinric and the test buttons seems to work, I already enable the skill in Alexa but I still cannot discover it

**Comment by aukris** [comment]
I am facing the same issue. Test buttons seem to be working (I can see a serial log) but Alexa can' t discover my ESP8266.

**Comment by kakopappa** [comment]
please check now

**Comment by aukris** [comment]
Still no luck, There are barely any logs. Can you please tell me how to debug this from my end? Like how does the discovery process work?

**Comment by kakopappa** [comment]
OK I will check this when I get back home from work. 

Meantime you should check out https://sinric.pro

**Comment by temocastro** [comment]
Same here, not discovering

**Comment by kakopappa** [comment]
please check again

**Comment by temocastro** [comment]
Ok now

**Comment by rpinoncely** [comment]
I worked now, thanks
