### ISSUE TITLE
When will Sinric stop working? so we will have to move to Sinric Pro, need deadlines

### ISSUE THREAD

**Issue by temocastro** [kakopappa/sinric#391]
@kakopappa When will Sinric stop working?, currently my Alexa is not Discovering Devices I just created in Sinric

**Comment by kakopappa** [comment]
Amazon changed something and it broke the device discovery. it's fixed now. 

you should consider moving to Pro.

**Comment by temocastro** [comment]
Working now, thanks, yes, will move to pro very soon
