### ISSUE TITLE
kakopappa brightness not updating on server.

### ISSUE THREAD

**Issue by harymk** [kakopappa/sinric#397]
void setBrightnessOnServer(String deviceId, int value) {
DynamicJsonDocument root(1024);
Serial.println(value);
root["deviceId"] = deviceId;
root["action"] = "SetBrightness";
root["value"] = value;
StreamString databuf;
serializeJson(root, databuf);
webSocket.sendTXT(databuf);
}

**Comment by kakopappa** [comment]
Check whether the device id is correct

Also you should consider moving to sinric v2 https://sinric.pro . If you
use the SDK in v2 you can avoid issues like this

**Comment by harymk** [comment]
kakopappa thanks. i forget that
