### ISSUE TITLE
Show device id 

### ISSUE THREAD

**Issue by kakopappa** [kakopappa/sinric#4]
Show device id of each device created in dashboard

**Comment by TheKerry** [comment]
Heyho, where can I see the ID of my created Device?

**Comment by kakopappa** [comment]
Right now it's not visible in the website. I am planing to fix this asap.
Sorry about that

Till then, when you invoke the device via Alexa, it is in the message you
receive.

String deviceId = json ["deviceId"];

So different devices will have different device id.

I will update this issue when it's fixed.

**Comment by TheKerry** [comment]
Allright, what exactly do you mean with that?
> Till then, when you invoke the device via Alexa, it is in the message you
receive.

When I go to Smart Home / Devices I can select my Device wich I created at sinric.com, but I can't see the ID of the Device.
Or is there a voice command to recive the Device ID?

**Comment by kakopappa** [comment]
Never mind, I just updated the UI to show the device id on the dashboard. 

Thanks

**Comment by TheKerry** [comment]
Great, thanks. Keep up the good work! :)
