### ISSUE TITLE
battery full turn off charger 

### ISSUE THREAD

**Issue by harymk** [kakopappa/sinric#419]
kakopappa how to set when battery fully charged turn of charger power android any idea

**Comment by kakopappa** [comment]
sorry about the late response. 

1. Create a  BroadcastReceiver and listen to Intent.ACTION_BATTERY_CHANGED
https://developer.android.com/training/monitoring-device-state/battery-monitoring

2. Send the turn off command to ESP module.
https://github.com/kakopappa/sinric/wiki

**Comment by kakopappa** [comment]
I think you can use IFTTT for this

**Comment by harymk** [comment]
I checked ifttt there is no option for battery Fully charged
