### ISSUE TITLE
(Sinric) Can't log in! :(

### ISSUE THREAD

**Issue by DaniloFloyd** [kakopappa/sinric#435]
Hello everyone!!

I've make a new account, trying to link it to my Amazon/Alexa, Skills, etç. It´s not accepting my key no matter what, neither on the app or the amazon sinric skill page.

Help please?

**Comment by kakopappa** [comment]
Not sure what you mean by “. It´s not accepting my key no matter what,”

You are suppose to enter your email/password for sinric here.

Make sure skill name is Sinric for sinric.com and Sinric Pro for sinric.pro

**Comment by DaniloFloyd** [comment]
> Not sure what you mean by “. It´s not accepting my key no matter what,”
> 
> You are suppose to enter your email/password for sinric here.
> 
> Make sure skill name is Sinric for sinric.com and Sinric Pro for sinric.pro
> …

((("Make sure skill name is Sinric for sinric.com and Sinric Pro for sinric.pro")))

Oh sir, thank you very much! Yes, i was confusing those two...how stupid!
Thanks again and have a great week!
