### ISSUE TITLE
One Wemos loosing connection

### ISSUE THREAD

**Issue by JanB97** [kakopappa/sinric#440]
Hi, one of my two wemos running sinric is loosing connect randomly since 3 or 4 days.
The other one is still working fine.
I did not change anything, is there a problem with the server?

**Comment by kakopappa** [comment]
I check the server. While checking i found out that one IP
address: 81.30.2.3 is sending too many messages. I blocked the IP. Please
check now

**Comment by JanB97** [comment]
Thank you, but it's still not working.
I'll try enabling the Serial output, maybe I can see something in there.

**Comment by JanB97** [comment]
I don't no why, but it started working again a frew weeks ago.
