### ISSUE TITLE
Unable to receive Alexa commands, and receiving  [WSc] Webservice disconnected from sinric.com! - on giving an action

### ISSUE THREAD

**Issue by ajarsco** [kakopappa/sinric#451]
Dear Kakopappa,
  is there any server issues on sinric.com, as on giving any actions through Alexa app it doesn't reflect in the esp32(any devices connected) and showing ---- [WSc] Webservice disconnected from sinric.com! in the serial monitor on giving any actions. 
Kindly reply faster.. its a bit urgent.

Waiting for your reply..

Akhil Jose

**Comment by kakopappa** [comment]
Try on a mobile hotspot

**Comment by ajarsco** [comment]
ok sir
I got it, it was due to unstable internet connection. I have changed my connection to fiber.. then it work smoothly...

thank you for your time sir :)
