### ISSUE TITLE
Devices no longer connecting

### ISSUE THREAD

**Issue by guicovred** [kakopappa/sinric#461]
Hi, I'm having issues to access the website and my devices just stopped working... is there a problem?

This started to happen a few days ago.

https://sinric.pro/pt-index.html: 
<img width="980" alt="Captura de Tela 2021-01-05 às 11 54 09" src="https://user-images.githubusercontent.com/51406604/103660879-de436680-4f4c-11eb-8ae1-6b6c5d878ddd.png">

**Comment by kakopappa** [comment]
@guicovred  your IP has been blocked because of it's making too many HTTP requests. do you have any scripts running?

**Comment by guicovred** [comment]
Well, no ... but my IP is not static, there may be some issue with my provider. I use just few devices in my home and turn they on / off only in Alexa

**Comment by kakopappa** [comment]
Well, one or more devices are crashing and rebooting and making too many requests to the server. Check the attached video

https://user-images.githubusercontent.com/7474406/103673866-a5d57400-4fb0-11eb-89df-b944ef1af66e.mp4

**Comment by guicovred** [comment]
This is sad. I will check, thank you very much for your attention so far.
