### ISSUE TITLE
Unable to login!

### ISSUE THREAD

**Issue by vaibhavbhange14** [kakopappa/sinric#469]
Issue logging in to sinric nor able to use device , it is showing device irresponsive.

**Comment by tonymrl** [comment]
Same issue, the server is not responding: Response with status: 502 OK for URL: https://sinric.com/api/v1/login

**Comment by vaibhavbhange14** [comment]
> Same issue, the server is not responding: Response with status: 502 OK for URL: https://sinric.com/api/v1/login

Try now! They restarted the server.
