### ISSUE TITLE
Problems with connecting. Exception (9)

### ISSUE THREAD

**Issue by 1237780** [kakopappa/sinric#472]
Hello,
I'm trying to control a light switch either with a ESP8266 ESP-12F or with a D1 Mini V3 NodeMCU.
I tried to load the example sketch "Switch" https://github.com/sinricpro/esp8266-esp32-sdk/tree/master/examples/Switch/Switch on both boards.
The connection with the WiFi is successful, but after that one i run into an exception.
The exact message is "Exception (9): epc1=0x40218607 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3fffff8b depc=0x00000000".
After that the whole content of the stack is printed.
After this the board is connecting with the WiFi again.
A screenshot of the Serial Monitor is attached.
Since the same thing happens with both boards and other programms are running with no problem I'm clueless.
Some help would be great.

Greetings and thank you for your help in advance.
![2021-02-16 (6)](https://user-images.githubusercontent.com/78730290/108121315-e7266c80-70a2-11eb-93cf-a01d68220999.png)

**Comment by sivar2311** [comment]
Please check for latest ESP Core Version (2.7.4) (Tools / Boards / Board Manger):
![image](https://user-images.githubusercontent.com/2558564/108121835-b0048b00-70a3-11eb-98e6-0e7cb943844c.png)
and latest webSockets Version (2.3.4) Library: Tools / Manage Libraries
![image](https://user-images.githubusercontent.com/2558564/108121986-e9d59180-70a3-11eb-88cc-58e77997c871.png)

**Comment by 1237780** [comment]
It was the older ESP Core Version, which I had to downgrade in the past for my last project.
I totally forgot about that one.
A big thanks for your very fast help and it's a great thing that you are doing with Sinric.
