### ISSUE TITLE
Not in Google home

### ISSUE THREAD

**Issue by MacGyver1rjq104** [kakopappa/sinric#6]
I don't see this app in google home but it states it will work?  Is this a mistake?

**Comment by kakopappa** [comment]
I didn't commit it yet. Still testing.

I will update the site soon

**Comment by Ameengray** [comment]
Can we use the same code to control a relay using node mcu or ESP01 ?

**Comment by drbeat** [comment]
Also curious if and how this may be possible

**Comment by JeffreyKlassen** [comment]
Google home support planned? I do not see anything on the main site.

**Comment by kakopappa** [comment]
yes, it's planned. need to fix few loose ends. I will update this issue when it's released.

**Comment by JeffreyKlassen** [comment]
Sounds good. Looking forward to it.

**Comment by kakopappa** [comment]
After a lot of work finally submitted to Google. fingers crossed.
 
![image](https://user-images.githubusercontent.com/7474406/37552648-1969be82-29ec-11e8-934f-90ac69318f56.png)

**Comment by kakopappa** [comment]
Once it get approved i will update the instructions on how to use.

**Comment by saikhurana** [comment]
Any Updates???
If it is still not updated, is there any dev version we can use to connect sinric with Google Home

**Comment by kakopappa** [comment]
Google home support added.
https://github.com/kakopappa/sinric/wiki/How-to-use-Google-Home
