### ISSUE TITLE
Pulse

### ISSUE THREAD

**Issue by GreenF0X** [kakopappa/sinric#69]
I figured out everything i need to know except how to pulse a button
I can pulse it in my programm but how do i get the button on amazon to turn of himself?
i do it like this.
So how can i tell amazon that the button is off
and also: how does it work if i want to have the control via alexa and an hardware button?
the whole programm is to control my Blinds which i want to control with software and hardware

![unbenannt](https://user-images.githubusercontent.com/40197759/41279276-4fc39230-6e2c-11e8-8131-9fe4a5f6400b.png)

best regards

**Comment by al8943** [comment]
`#include <WebSocketsClient.h> //  get it from https://github.com/Links2004/arduinoWebSockets/releases 
#include <ArduinoJson.h> // get it from https://arduinojson.org/ or install via Arduino library manager
#include <StreamString.h> 



#define DeviceID "change" // Device ID from sinric.com
#define MyApiKey "change" // Your API Key is displayed on sinric.com dashboard
bool LastState = false;
bool CurrentState = false;
void setPowerStateOnServer(String deviceId, String value);
WebSocketsClient webSocket;



void setup() {

}

void loop() {
  
//publish
CurrentState = digitalRead(4);

if (LastState != CurrentState){
  if (CurrentState == HIGH){
      setPowerStateOnServer(DeviceID, "ON");
      }
   else{
      setPowerStateOnServer(DeviceID, "OFF");
     }
   LastState = CurrentState;
}
}


void setPowerStateOnServer(String deviceId, String value) {
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.createObject();
  root["deviceId"] = deviceId;
  root["action"] = "setPowerState";
  root["value"] = value;
  StreamString databuf;
  root.printTo(databuf);
  
  webSocket.sendTXT(databuf);
}


`

**Comment by GreenF0X** [comment]
i allways get 

exit status 1
'DeviceID' was not declared in this scope

**Comment by kakopappa** [comment]
If you want to let the Amazon know about the current status, you have to update the button status on Sinric server. You can do this with above setPowerStateOnServer function (above post). So when next Amazon periodically calls to check the status it will be updated.

**Comment by GreenF0X** [comment]
But i cant do it like in the code above because i get the error above

**Comment by GreenF0X** [comment]
???????

**Comment by al8943** [comment]
I copied and pasted the code I posted earlier into a new sketch and it compiles without error.

**Comment by kakopappa** [comment]
![image](https://user-images.githubusercontent.com/7474406/41541809-889d1958-733d-11e8-9221-147fb19dfe79.png)

compiles fine for me too.

You should download Arduino 1.8.5 and try again

**Comment by GreenF0X** [comment]
ok now i updated all boards and libraries and now i get the error message 
ESP8266WiFi.h: No such file or directory

**Comment by kakopappa** [comment]
Pick the correct board

**Comment by GreenF0X** [comment]
oh yeah sorry
but now i get this


Arduino: 1.8.2 (Windows 10), Board: "WeMos D1 R1, 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

C:\Users\FSiTe2\AppData\Local\Temp\arduino_modified_sketch_172489\test_sinric_code.ino: In function 'void setPowerStateOnServer(String, String)':

test_sinric_code:34: error: 'DynamicJsonBuffer' was not declared in this scope

 DynamicJsonBuffer jsonBuffer;

 ^

C:\Users\FSiTe2\AppData\Local\Temp\arduino_modified_sketch_172489\test_sinric_code.ino:34:1: note: suggested alternative:

In file included from C:\Users\FSiTe2\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/DynamicJsonDocument.hpp:10:0,

                 from C:\Users\FSiTe2\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:9,

                 from C:\Users\FSiTe2\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\FSiTe2\AppData\Local\Temp\arduino_modified_sketch_172489\test_sinric_code.ino:2:

C:\Users\FSiTe2\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/DynamicJsonBuffer.hpp:159:5: note:   'ArduinoJson::Internals::DynamicJsonBuffer'

     DynamicJsonBuffer;

     ^

test_sinric_code:34: error: expected ';' before 'jsonBuffer'

 DynamicJsonBuffer jsonBuffer;

                   ^

test_sinric_code:35: error: 'jsonBuffer' was not declared in this scope

 JsonObject& root = jsonBuffer.createObject();

                    ^

test_sinric_code:40: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

 root.printTo(databuf);

      ^

exit status 1
'DynamicJsonBuffer' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by GreenF0X** [comment]
![grafik](https://user-images.githubusercontent.com/40197759/41583789-cec52ade-73a5-11e8-8cf1-6061136669e8.png)

**Comment by kakopappa** [comment]
Likely json library is not installed correctly. Follow my previous
instructions

**Comment by GreenF0X** [comment]
now my programm which worked before also gives me the same error code
maybe it was a mistake to update boards and libraries ;(

**Comment by GreenF0X** [comment]
what version of json should i use?
i updated to the 6.0.1 beta today

**Comment by GreenF0X** [comment]
now i have 5.13.2
still the same error

**Comment by kakopappa** [comment]
https://arduinojson.org/v5/doc/installation/

ArduinoJson 5.13.2

**Comment by kakopappa** [comment]
try reloading arduino IDE

**Comment by GreenF0X** [comment]
i did before
nothing changed
restarted pc now it works :D
coming back when im done programming :D

**Comment by GreenF0X** [comment]
so now i set up everything
but it still wont update my status on Alexa

`if (digitalRead(14)==HIGH)
{
setPowerStateOnServer("5b275c70fde9453a049b0aa3", "ON");
}`
`if (digitalRead(12)==HIGH)
{
setPowerStateOnServer("5b275c70fde9453a049b0aa3", "OFF");
}`

the esp get from my arduino if my shades are open or closed
so if Pin 14 is HIGH it means my shades are open and the switch in alexa should turn from off to on

**Comment by GreenF0X** [comment]
????
