### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by samhorne2** [kakopappa/sinric#7]
I try to register, then try to login and the site says "user not found".

**Comment by kakopappa** [comment]
i just tried registering for a new account and it worked. 

Can you try with another email? email does not have to be a real one. fake one will do. Just use the same email when you link with the alexa smart home skill

**Comment by samhorne2** [comment]
Wow thanks for the fast help! It was my browser. Chrome worked, not Safari.

**Comment by samhorne2** [comment]
I look forward to using this service!

**Comment by kakopappa** [comment]
interesting... thank you for letting me know

I will reopen this issue to check later
