### ISSUE TITLE
How to use Google Home [instruction improvement]

### ISSUE THREAD

**Issue by Deimos1994** [kakopappa/sinric#74]
https://github.com/kakopappa/sinric/wiki/How-to-use-Google-Home
It says: "Without this when you add or remove a device, you must unlink the account and relink the account to work properly"
Actualy we can just ask google home: **"hey, google sync my devices"** than it answers **"You got it, syncing devices for Sinric."**.

**Comment by kakopappa** [comment]
doc updated. thanks
