### ISSUE TITLE
message from google "sinric is not accessible "

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#79]
Hi 
every day (24 Hrs) I am getting a message can't access SINRIC  so I unlink my account then relink it to get sinric  working again.
Is that correct ?
Thank you for your good work.

**Comment by pico563** [comment]
after a month now 
message from google "sinric is not accessible "

**Comment by Andreslion** [comment]
I'm still getting only 24h of connection to Sinric on Google home. 
Is there any way of not having to unlink-relink every day?
