### ISSUE TITLE
Multiple devices on a single 8266?

### ISSUE THREAD

**Issue by DSSCircuits** [kakopappa/sinric#8]
Will the code support multiple devices on the same ESP8266?  I have been using your other wemo switch software (great job by the way!!!), except it starts having connection issues when I get up to 4 device ID's.

Will this new skill support multiple device ID's? It's a little confusing trying to reference the example.  

Thanks again!!!

**Comment by kakopappa** [comment]
Multiple switches will have a different device id.  Each device you create on the website has a unique device id. Unfortunately, this device id is not shown on the website. I will fix this. 

https://github.com/kakopappa/sinric/blob/master/arduino_examples/switch_example.ino#L38

Check the device id and code your logic accordingly.

**Comment by kakopappa** [comment]
@DSSCircuits 

I have updated the UI to show the device id now.
