### ISSUE TITLE
Issue with "play" command - TV

### ISSUE THREAD

**Issue by AshokBaijal** [kakopappa/sinric#81]
I have made an ESP8266 IR controller for my Philips Soundbar. While most of the commands are working Alexa is finding it a problem to respond to the "PLAY" command as the command gets diverted to the Music App which comes with Alexa and starts playing music by some group called Soundbars. This is an Amazon issue. I am trying to contact them. Just keeping the community in the loop and if someone can suggest a solution.

Attaching the code for the IR controller
(Deleted)

**Comment by mmphego** [comment]
Dude Note that your api key is on the file...
Serious security issue

**Comment by AshokBaijal** [comment]
Sorry buddy, oversight. Code deleted.

**Comment by AshokBaijal** [comment]
Got a call from Amazon Support. They have suggested to change the device name from Soundbar to something else. Let me experiment further.

**Comment by AshokBaijal** [comment]
Tried after changing the device name. However, Alexa responds to the Play command by invoking the Music Skill. 

This is an Amazon issue and not Sinric issue. As such closing the issue here.
