### ISSUE TITLE
Minor Issue - Udate "Supported-devices-and-their-capabilities"

### ISSUE THREAD

**Issue by mrmonteith** [kakopappa/sinric#84]
I was looking at that Wiki page and from viewing the closed issues that some more capabilities are there but not linked.

 [https://github.com/kakopappa/sinric/wiki/Supported-devices-and-their-capabilities.](url)

 I think Alexa.PlaybackController was one of them.

**Comment by kakopappa** [comment]
Thanks.

I will update this page on this weekend with Amazon / Google Home
https://github.com/kakopappa/sinric/wiki/Supported-devices-and-their-capabilities.

**Comment by kakopappa** [comment]
Page updated.
