### ISSUE TITLE
You are not eligible to enable this skill due to geographical restrictions

### ISSUE THREAD

**Issue by IOTHobby** [kakopappa/sinric#9]
Thanks for sharing Kakopappa!

Trying to get Sinric skill, getting this message
"You are not eligible to enable this skill due to geographical restrictions."

Is there is a restriction to get skill?

**Comment by kakopappa** [comment]
I think it's available for US only at the moment. I am in the process of
supporting other countries. ( Germany and India)

Where are you from? Drop me your email address and I will send you an
invite(not sure that will work)

**Comment by IOTHobby** [comment]
Vancouver, Canada.

**Comment by kakopappa** [comment]
send me your email. I will send you an invite to beta test. That might work

**Comment by IOTHobby** [comment]
rajat.soni@gmail.com

**Comment by kakopappa** [comment]
I just sent you an invite. please check

**Comment by IOTHobby** [comment]
Thanks a lot!! It works, was able to connect device with echo and send commands. Will try adding more nodemcu devices and start using them!

**Comment by TetsudouSenpai** [comment]
Hi @kakopappa ! Would it be possible for me to also join beta testing? I'm from the UK, my email is dimaleyko@gmail.com .

Thank you very much in advance!

**Comment by kakopappa** [comment]
@TetsudouSenpai sent

**Comment by robsorn** [comment]
Hi @kakopappa, connecting to your service worked like a charm. However, I also can't find the skill.
Would you mind sending me a beta-testing invitation to krsstk@gmail.com (Located in Germany)?
