### ISSUE TITLE
new Sinric update not working with Alexa  but GH works OK.

### ISSUE THREAD

**Issue by pico563** [kakopappa/sinric#93]
Hello kakopappa
with Alexa
[WSc] get text: {"deviceId":"xxxx","action":"setPowerState","value":"ON"}
[WSc] get text: {"deviceId":"xxxx","action":"setPowerState","value":"OFF"}

with  Sinric application
[WSc] get text: {"deviceId":"xxxx","action":"powerState","value":"OFF"}
[WSc] get text: {"deviceId":"xxxx","action":"powerState","value":"ON"}

I think you missed the world "set"

Thanks

**Comment by kakopappa** [comment]
@pico563 Thanks 

I fixed the command formats accordingly. I have fixed these issues in app (v3.0) . It will be available on Google Play to update shortly.

https://github.com/kakopappa/sinric/issues/88
